"""Rotating topic pool for daily biblical story video generation."""

TOPICS = [
    "David and Goliath",
    "Noah's Ark and the great flood",
    "Daniel in the lion's den",
    "Jonah and the whale",
    "Moses parting the Red Sea",
    "The Ten Commandments given to Moses",
    "Joseph and his coat of many colors",
    "Samson and Delilah",
    "The Tower of Babel",
    "Adam and Eve in the Garden of Eden",
    "Cain and Abel",
    "Abraham and Isaac",
    "Jacob wrestling with the angel",
    "The Exodus from Egypt",
    "Joshua and the walls of Jericho",
    "Ruth and Naomi's loyalty",
    "David and Bathsheba",
    "Solomon's wisdom and the two mothers",
    "Elijah and the prophets of Baal",
    "Esther saving her people",
    "The Nativity - the birth of Jesus",
    "The Wise Men following the star",
    "Jesus turning water into wine",
    "Jesus feeding the five thousand",
    "Jesus calming the storm",
    "The Good Samaritan",
    "The Prodigal Son",
    "Jesus and the woman at the well",
    "Lazarus raised from the dead",
    "The Last Supper",
    "The crucifixion and resurrection of Jesus",
    "Doubting Thomas",
    "The road to Emmaus",
    "Paul's conversion on the road to Damascus",
    "Peter walking on water",
]
