"""Rotating topic pool for daily biblical story video generation."""

TOPICS = [
    "David and Goliath",
    "Noah's Ark and the great flood",
    "Daniel in the lion's den",
    "Jonah and the whale",
    "Moses parting the Red Sea",
    "The Ten Commandments given to Moses",
    "Joseph and his coat of many colors",
    "Samson and Delilah",
    "The Tower of Babel",
    "Adam and Eve in the Garden of Eden",
    "Cain and Abel",
    "Abraham and Isaac",
    "Jacob wrestling with the angel",
    "The Exodus from Egypt",
    "Joshua and the walls of Jericho",
    "Ruth and Naomi's loyalty",
    "David and Bathsheba",
    "Solomon's wisdom and the two mothers",
    "Elijah and the prophets of Baal",
    "Esther saving her people",
    "The Nativity - the birth of Jesus",
    "The Wise Men following the star",
    "Jesus turning water into wine",
    "Jesus feeding the five thousand",
    "Jesus calming the storm",
    "The Good Samaritan",
    "The Prodigal Son",
    "Jesus and the woman at the well",
    "Lazarus raised from the dead",
    "The Last Supper",
    "The crucifixion and resurrection of Jesus",
    "Doubting Thomas",
    "The road to Emmaus",
    "Paul's conversion on the road to Damascus",
    "Peter walking on water",
    "The angel Gabriel announcing Jesus's birth to Mary",
    "An angel appearing to the shepherds to announce Jesus's birth",
    "Jacob's ladder - a stairway to heaven with angels ascending and descending",
    "The angel Michael and the war in heaven against the dragon",
    "An angel freeing Peter from prison",
    "Angels ministering to Jesus after his temptation in the desert",
    "The angel rolling away the stone at Jesus's tomb",
    "Jesus's parable of the Kingdom of Heaven as a mustard seed",
    "Jesus's parable of the Kingdom of Heaven as a hidden treasure",
    "Jesus's parable of the ten virgins waiting for the bridegroom",
    "The vision of the heavenly city, the New Jerusalem",
    "The angel who wrestled with Jacob at Peniel",
    "An angel appearing to Joseph in a dream to warn him of danger",
    "The heavenly host praising God at Jesus's birth",
    "John's vision of the New Jerusalem descending from heaven in Revelation",
    "John's vision of the throne room of heaven and the twenty-four elders in Revelation",
    "John's vision of the river of the water of life and the tree of life in Revelation",
    "John's vision in Revelation that there will be no more death, mourning, or pain in heaven",
    "John's vision of the wedding feast of the Lamb in Revelation",
    "John's vision of the gates of pearl and streets of gold in Revelation",
    "John's vision of every tribe and nation worshiping together before God's throne in Revelation",
]
